import 'package:editor_app/model/filter.dart';

class Filters {
  List<Filter> list() {
    return <Filter>[
      Filter(
          filterName: 'purple',
          matrix: [1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0]),
      Filter(filterName: 'purple', matrix: [
        1,
        0,
        0,
        0,
        0,
        0,
        1,
        0,
        0,
        0,
        -0.2,
        0.2,
        0.1,
        0.4,
        0,
        0,
        0,
        0,
        1,
        0
      ]),
      Filter(
          filterName: 'purple',
          matrix: [0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0]),
      Filter(filterName: 'purple', matrix: [
        1,
        0,
        0,
        1.9,
        -2.2,
        0,
        1,
        0,
        0.0,
        0.3,
        0,
        0,
        1,
        0,
        0.5,
        0,
        0,
        0,
        1,
        0.2
      ]),
      Filter(filterName: 'red', matrix: [
        1,
        -0.2,
        0,
        0,
        0,
        0,
        1,
        0,
        -0.1,
        0,
        0,
        1.2,
        1,
        0.1,
        0,
        0,
        0,
        1.7,
        1,
        0
      ]),
      Filter(filterName: 'red', matrix: [
        1,
        0,
        0,
        0,
        0,
        -0.2,
        1.0,
        0.3,
        0.1,
        0,
        -0.1,
        0,
        1,
        0,
        0,
        0,
        0,
        0,
        1,
        0
      ]),
    ];
  }
}
